-- ERDCloud Import / MySQL 8.0+
-- 사용법: ERDCloud 하단 Import를 열고 이 파일의 DDL 전체를 붙여넣는다.
-- 선행 엔티티: MEMBER(MEMBER_ID BIGINT), ACCOUNT(ACCOUNT_ID BIGINT)
-- MEMBER와 ACCOUNT가 대상 ERD에 이미 존재해야 외부 FK 관계가 연결된다.

CREATE TABLE PRODUCT (
    PRODUCT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상품 식별자',
    PRODUCT_NAME VARCHAR(100) NOT NULL COMMENT '상품명',
    PRODUCT_TYPE VARCHAR(20) NOT NULL COMMENT 'DEPOSIT: 예금, SAVINGS: 적금',
    BASE_INTEREST_RATE DECIMAL(7,4) NOT NULL COMMENT '기본 연이율(%)',
    PREFERENTIAL_CONDITION VARCHAR(500) NULL COMMENT '우대금리 조건',
    TERM_MONTHS SMALLINT UNSIGNED NOT NULL COMMENT '가입 기간(개월)',
    MINIMUM_AMOUNT BIGINT UNSIGNED NOT NULL COMMENT '최소 가입금액',
    EARLY_TERMINATION_RATE DECIMAL(7,4) NOT NULL DEFAULT 0 COMMENT '중도해지 연이율(%)',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT CK_PRODUCT_TYPE CHECK (PRODUCT_TYPE IN ('DEPOSIT', 'SAVINGS')),
    CONSTRAINT CK_PRODUCT_RATE CHECK (BASE_INTEREST_RATE BETWEEN 0 AND 100),
    CONSTRAINT CK_PRODUCT_EARLY_RATE CHECK (EARLY_TERMINATION_RATE BETWEEN 0 AND 100),
    CONSTRAINT CK_PRODUCT_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='예금/적금 상품 마스터';

CREATE TABLE PRODUCT_SUBSCRIPTION (
    SUBSCRIPTION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상품 가입 식별자',
    MEMBER_ID BIGINT NOT NULL COMMENT '가입 회원 식별자',
    PRODUCT_ID BIGINT NOT NULL COMMENT '가입 상품 식별자',
    ACCOUNT_ID BIGINT NOT NULL COMMENT '예적금 전용 계좌 식별자',
    PRINCIPAL_AMOUNT BIGINT UNSIGNED NOT NULL COMMENT '예금 가입액 또는 적금 목표 원금',
    MONTHLY_PAYMENT BIGINT UNSIGNED NULL COMMENT '적금 월 납입액, 예금은 NULL',
    SUBSCRIBED_AT DATE NOT NULL COMMENT '가입일',
    MATURITY_DATE DATE NOT NULL COMMENT '만기일',
    EXPECTED_INTEREST BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '예상 세전 이자',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, MATURED, CANCELLED',
    CANCELLED_AT DATETIME NULL COMMENT '중도해지 일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT PK_PRODUCT_SUB PRIMARY KEY (SUBSCRIPTION_ID),
    CONSTRAINT UK_PRODUCT_SUB_ACCOUNT UNIQUE (ACCOUNT_ID),
    CONSTRAINT CK_PRODUCT_SUB_STATUS CHECK (STATUS IN ('ACTIVE', 'MATURED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원의 예금/적금 가입 내역';

CREATE TABLE CARD (
    CARD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '카드 식별자',
    MEMBER_ID BIGINT NOT NULL COMMENT '카드 소유 회원 식별자',
    ACCOUNT_ID BIGINT NOT NULL COMMENT '결제 연결 계좌 식별자',
    CARD_NUMBER VARCHAR(19) NOT NULL COMMENT '프로젝트용 mock 카드번호',
    CARD_TYPE VARCHAR(20) NOT NULL COMMENT 'CHECK, CREDIT',
    CARD_NAME VARCHAR(100) NOT NULL COMMENT '카드 상품명',
    CREDIT_LIMIT BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '카드 이용한도',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'APPLIED' COMMENT 'APPLIED, ACTIVE, SUSPENDED, LOST, CANCELLED',
    ISSUED_AT DATE NULL COMMENT '발급일',
    EXPIRES_AT DATE NULL COMMENT '유효기간 만료일',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT PK_CARD PRIMARY KEY (CARD_ID),
    CONSTRAINT UK_CARD_NUMBER UNIQUE (CARD_NUMBER),
    CONSTRAINT CK_CARD_TYPE CHECK (CARD_TYPE IN ('CHECK', 'CREDIT')),
    CONSTRAINT CK_CARD_STATUS CHECK (STATUS IN ('APPLIED', 'ACTIVE', 'SUSPENDED', 'LOST', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원 카드 신청 및 발급 정보';

CREATE TABLE CARD_USAGE_HISTORY (
    CARD_USAGE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '카드 사용내역 식별자',
    CARD_ID BIGINT NOT NULL COMMENT '카드 식별자',
    MERCHANT_NAME VARCHAR(100) NOT NULL COMMENT '가맹점명',
    MERCHANT_CATEGORY VARCHAR(50) NULL COMMENT '가맹점 분류',
    AMOUNT BIGINT UNSIGNED NOT NULL COMMENT '사용금액',
    USED_AT DATETIME NOT NULL COMMENT '사용일시',
    APPROVAL_NUMBER VARCHAR(30) NOT NULL COMMENT '프로젝트용 승인번호',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'APPROVED' COMMENT 'APPROVED, CANCELLED',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    CONSTRAINT PK_CARD_USAGE PRIMARY KEY (CARD_USAGE_ID),
    CONSTRAINT UK_CARD_USAGE_APPROVAL UNIQUE (APPROVAL_NUMBER),
    CONSTRAINT CK_CARD_USAGE_STATUS CHECK (STATUS IN ('APPROVED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='프로젝트용 카드 사용내역';

CREATE TABLE LOAN (
    LOAN_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '대출 식별자',
    MEMBER_ID BIGINT NOT NULL COMMENT '대출 신청 회원 식별자',
    REPAYMENT_ACCOUNT_ID BIGINT NOT NULL COMMENT '대출금 입금 및 상환 계좌 식별자',
    LOAN_TYPE VARCHAR(30) NOT NULL COMMENT 'CREDIT, MORTGAGE, JEONSE',
    REQUESTED_AMOUNT BIGINT UNSIGNED NOT NULL COMMENT '신청금액',
    APPROVED_AMOUNT BIGINT UNSIGNED NULL COMMENT '승인금액',
    ANNUAL_INTEREST_RATE DECIMAL(7,4) NULL COMMENT '승인 연이율(%)',
    TERM_MONTHS SMALLINT UNSIGNED NOT NULL COMMENT '대출기간(개월)',
    REPAYMENT_METHOD VARCHAR(30) NOT NULL COMMENT 'EQUAL_PAYMENT, EQUAL_PRINCIPAL, BULLET',
    EMPLOYMENT_STATUS VARCHAR(30) NOT NULL COMMENT 'EMPLOYED, SELF_EMPLOYED, UNEMPLOYED, OTHER',
    ANNUAL_INCOME BIGINT UNSIGNED NOT NULL COMMENT '연 소득',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'APPLIED' COMMENT 'APPLIED, APPROVED, REJECTED, REPAYING, REPAID, CANCELLED',
    REVIEWED_BY BIGINT NULL COMMENT '심사 관리자 회원 식별자',
    APPLIED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '신청일시',
    REVIEWED_AT DATETIME NULL COMMENT '심사일시',
    STARTED_AT DATE NULL COMMENT '대출 실행일',
    MATURITY_DATE DATE NULL COMMENT '대출 만기일',
    REJECTION_REASON VARCHAR(500) NULL COMMENT '거절 사유',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT PK_LOAN PRIMARY KEY (LOAN_ID),
    CONSTRAINT CK_LOAN_TYPE CHECK (LOAN_TYPE IN ('CREDIT', 'MORTGAGE', 'JEONSE')),
    CONSTRAINT CK_LOAN_METHOD CHECK (REPAYMENT_METHOD IN ('EQUAL_PAYMENT', 'EQUAL_PRINCIPAL', 'BULLET')),
    CONSTRAINT CK_LOAN_EMPLOYMENT CHECK (EMPLOYMENT_STATUS IN ('EMPLOYED', 'SELF_EMPLOYED', 'UNEMPLOYED', 'OTHER')),
    CONSTRAINT CK_LOAN_STATUS CHECK (STATUS IN ('APPLIED', 'APPROVED', 'REJECTED', 'REPAYING', 'REPAID', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='대출 신청, 심사 및 계약 정보';

CREATE TABLE LOAN_REPAYMENT_SCHEDULE (
    SCHEDULE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상환 일정 식별자',
    LOAN_ID BIGINT NOT NULL COMMENT '대출 식별자',
    INSTALLMENT_NO SMALLINT UNSIGNED NOT NULL COMMENT '상환 회차',
    DUE_DATE DATE NOT NULL COMMENT '상환 예정일',
    PRINCIPAL_AMOUNT BIGINT UNSIGNED NOT NULL COMMENT '상환 원금',
    INTEREST_AMOUNT BIGINT UNSIGNED NOT NULL COMMENT '상환 이자',
    TOTAL_AMOUNT BIGINT UNSIGNED NOT NULL COMMENT '총 상환금액',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED' COMMENT 'SCHEDULED, PAID, OVERDUE, WAIVED',
    PAID_AT DATETIME NULL COMMENT '실제 상환일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT PK_LOAN_REPAY_SCHEDULE PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT UK_LOAN_REPAY_INSTALLMENT UNIQUE (LOAN_ID, INSTALLMENT_NO),
    CONSTRAINT CK_LOAN_REPAY_STATUS CHECK (STATUS IN ('SCHEDULED', 'PAID', 'OVERDUE', 'WAIVED')),
    CONSTRAINT CK_LOAN_REPAY_TOTAL CHECK (TOTAL_AMOUNT = PRINCIPAL_AMOUNT + INTEREST_AMOUNT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='대출 회차별 상환 일정';

CREATE INDEX IX_PRODUCT_SUB_MEMBER ON PRODUCT_SUBSCRIPTION (MEMBER_ID);
CREATE INDEX IX_PRODUCT_SUB_PRODUCT ON PRODUCT_SUBSCRIPTION (PRODUCT_ID);
CREATE INDEX IX_CARD_MEMBER ON CARD (MEMBER_ID);
CREATE INDEX IX_CARD_ACCOUNT ON CARD (ACCOUNT_ID);
CREATE INDEX IX_CARD_USAGE_CARD_DATE ON CARD_USAGE_HISTORY (CARD_ID, USED_AT);
CREATE INDEX IX_LOAN_MEMBER_STATUS ON LOAN (MEMBER_ID, STATUS);
CREATE INDEX IX_LOAN_REPAY_ACCOUNT ON LOAN (REPAYMENT_ACCOUNT_ID);
CREATE INDEX IX_LOAN_REVIEWER ON LOAN (REVIEWED_BY);
CREATE INDEX IX_LOAN_REPAY_DUE_DATE ON LOAN_REPAYMENT_SCHEDULE (LOAN_ID, DUE_DATE);

ALTER TABLE PRODUCT_SUBSCRIPTION
    ADD CONSTRAINT FK_PRODUCT_SUB_MEMBER
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    ADD CONSTRAINT FK_PRODUCT_SUB_PRODUCT
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    ADD CONSTRAINT FK_PRODUCT_SUB_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID);

ALTER TABLE CARD
    ADD CONSTRAINT FK_CARD_MEMBER
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    ADD CONSTRAINT FK_CARD_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID);

ALTER TABLE CARD_USAGE_HISTORY
    ADD CONSTRAINT FK_CARD_USAGE_CARD
        FOREIGN KEY (CARD_ID) REFERENCES CARD (CARD_ID);

ALTER TABLE LOAN
    ADD CONSTRAINT FK_LOAN_MEMBER
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    ADD CONSTRAINT FK_LOAN_REPAY_ACCOUNT
        FOREIGN KEY (REPAYMENT_ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
    ADD CONSTRAINT FK_LOAN_REVIEWER
        FOREIGN KEY (REVIEWED_BY) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE LOAN_REPAYMENT_SCHEDULE
    ADD CONSTRAINT FK_LOAN_REPAY_LOAN
        FOREIGN KEY (LOAN_ID) REFERENCES LOAN (LOAN_ID);

