-- =====================================================================
-- 팀원1 담당 테이블 DDL (Oracle)
--   고객: MEMBER, IDENTITY_VERIFICATION, LOGIN_LOG, TRANSFER_LIMIT_REQUEST
--   직원: EMPLOYEE, EMPLOYEE_LOGIN_LOG
--   공통: BRANCH (지점/ATM, 직원 소속 지점), BRANCH_SERVICE (이용 가능 업무)
--
-- 고객(MEMBER)과 직원(EMPLOYEE)은 테이블과 로그인을 완전히 분리한다.
-- 직원 권한 3단계: STAFF(일반 직원) / MANAGER(책임자) / SYSTEM_ADMIN(시스템 관리자)
--
-- 실행 순서: 이 파일 → 다른 팀원 DDL(ACCOUNT 등) → 파일 맨 아래 "ACCOUNT 생성 후 실행" 블록
-- 공통 규칙: README 10-1장 참고
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. MEMBER : 고객 회원 (직원은 EMPLOYEE 테이블)
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MEMBER (
    MEMBER_ID           NUMBER(19)          NOT NULL,
    LOGIN_ID            VARCHAR2(30 CHAR)   NOT NULL,
    PASSWORD            VARCHAR2(100)       NOT NULL,
    NAME                VARCHAR2(30 CHAR)   NOT NULL,
    EMAIL               VARCHAR2(100 CHAR)  NOT NULL,
    PHONE               VARCHAR2(20)        NOT NULL,
    BIRTH_DATE          DATE                NOT NULL,
    STATUS              VARCHAR2(20)        DEFAULT 'ACTIVE' NOT NULL,
    VERIFICATION_STATUS VARCHAR2(20)        DEFAULT 'NONE'   NOT NULL,
    LOGIN_FAIL_COUNT    NUMBER(2)           DEFAULT 0        NOT NULL,
    LOGIN_LOCKED_AT     TIMESTAMP,
    TERMS_AGREED_AT     TIMESTAMP           NOT NULL,
    MARKETING_AGREE_YN  CHAR(1)             DEFAULT 'N'      NOT NULL,
    CREATED_AT          TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP,
    WITHDRAWN_AT        TIMESTAMP,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UK_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_MEMBER_PHONE UNIQUE (PHONE),
    CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    CONSTRAINT CK_MEMBER_VERIFICATION CHECK (VERIFICATION_STATUS IN ('NONE', 'PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT CK_MEMBER_MARKETING CHECK (MARKETING_AGREE_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  MEMBER IS '고객 회원 (직원은 EMPLOYEE)';
COMMENT ON COLUMN MEMBER.LOGIN_ID IS '로그인 아이디 - 탈퇴 후에도 재사용 불가';
COMMENT ON COLUMN MEMBER.PASSWORD IS 'BCrypt 해시';
COMMENT ON COLUMN MEMBER.PHONE IS '숫자만 저장. 탈퇴 시 마스킹';
COMMENT ON COLUMN MEMBER.VERIFICATION_STATUS IS '본인확인 상태: NONE 미확인 / PENDING 심사중 / VERIFIED 완료 / REJECTED 반려';
COMMENT ON COLUMN MEMBER.LOGIN_LOCKED_AT IS '로그인 5회 실패 잠금 시각. NULL이면 잠기지 않음';


-- ---------------------------------------------------------------------
-- 2. BRANCH : 지점/ATM (직원의 소속 지점으로도 사용 → EMPLOYEE보다 먼저 생성)
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_BRANCH START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE BRANCH (
    BRANCH_ID           NUMBER(19)          NOT NULL,
    BRANCH_TYPE         VARCHAR2(10)        NOT NULL,
    NAME                VARCHAR2(50 CHAR)   NOT NULL,
    ADDRESS             VARCHAR2(200 CHAR)  NOT NULL,
    LATITUDE            NUMBER(10, 7)       NOT NULL,
    LONGITUDE           NUMBER(10, 7)       NOT NULL,
    PHONE               VARCHAR2(20),
    BUSINESS_HOURS      VARCHAR2(50 CHAR),
    OPEN_24H_YN         CHAR(1)             DEFAULT 'N' NOT NULL,
    USE_YN              CHAR(1)             DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_ID),
    CONSTRAINT CK_BRANCH_TYPE CHECK (BRANCH_TYPE IN ('BRANCH', 'ATM')),
    CONSTRAINT CK_BRANCH_OPEN_24H CHECK (OPEN_24H_YN IN ('Y', 'N')),
    CONSTRAINT CK_BRANCH_USE CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_BRANCH_LAT CHECK (LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CK_BRANCH_LNG CHECK (LONGITUDE BETWEEN -180 AND 180)
);

CREATE INDEX IX_BRANCH_TYPE ON BRANCH (BRANCH_TYPE, USE_YN);

COMMENT ON TABLE  BRANCH IS '지점/ATM (본점 포함)';
COMMENT ON COLUMN BRANCH.USE_YN IS '삭제 대신 미사용(N) 처리';


-- ---------------------------------------------------------------------
-- 2-1. BRANCH_SERVICE : 지점/ATM 이용 가능 업무 (지점 1곳에 업무 여러 개)
--    JPA: Branch.services (@ElementCollection + BranchServiceType enum)
--    계좌개설/대출상담/카드발급은 창구 업무라 ATM에 등록 불가 → Entity에서 검사
-- ---------------------------------------------------------------------
CREATE TABLE BRANCH_SERVICE (
    BRANCH_ID           NUMBER(19)          NOT NULL,
    SERVICE_CODE        VARCHAR2(30)        NOT NULL,
    CONSTRAINT PK_BRANCH_SERVICE PRIMARY KEY (BRANCH_ID, SERVICE_CODE),
    CONSTRAINT FK_BRANCH_SERVICE_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID),
    CONSTRAINT CK_BRANCH_SERVICE_CODE CHECK (SERVICE_CODE IN (
        'DEPOSIT', 'WITHDRAW', 'TRANSFER', 'BALANCE_INQUIRY',
        'ACCOUNT_OPENING', 'LOAN_CONSULTING', 'CARD_ISSUANCE'
    ))
);

-- "입금 가능한 곳" 같은 업무별 필터 (PK는 BRANCH_ID가 앞이라 이 검색에 못 씀)
CREATE INDEX IX_BRANCH_SERVICE_CODE ON BRANCH_SERVICE (SERVICE_CODE, BRANCH_ID);

COMMENT ON TABLE  BRANCH_SERVICE IS '지점/ATM 이용 가능 업무';
COMMENT ON COLUMN BRANCH_SERVICE.SERVICE_CODE IS 'DEPOSIT 입금 / WITHDRAW 출금 / TRANSFER 이체 / BALANCE_INQUIRY 잔액조회 / ACCOUNT_OPENING 계좌개설 / LOAN_CONSULTING 대출상담 / CARD_ISSUANCE 카드발급';


-- ---------------------------------------------------------------------
-- 3. EMPLOYEE : 은행 직원 (관리자 화면 /admin/** 사용자)
--    ROLE   : STAFF 일반 직원 / MANAGER 책임자 / SYSTEM_ADMIN 시스템 관리자
--    POSITION(직급)은 화면 표시용이며 권한과 무관하다
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID         NUMBER(19)          NOT NULL,
    EMPLOYEE_NO         VARCHAR2(10)        NOT NULL,
    PASSWORD            VARCHAR2(100)       NOT NULL,
    NAME                VARCHAR2(30 CHAR)   NOT NULL,
    EMAIL               VARCHAR2(100 CHAR)  NOT NULL,
    PHONE               VARCHAR2(20),
    BRANCH_ID           NUMBER(19)          NOT NULL,
    POSITION            VARCHAR2(20 CHAR)   NOT NULL,
    ROLE                VARCHAR2(20)        DEFAULT 'STAFF'  NOT NULL,
    STATUS              VARCHAR2(20)        DEFAULT 'ACTIVE' NOT NULL,
    TEMP_PW_YN          CHAR(1)             DEFAULT 'Y'      NOT NULL,
    LOGIN_FAIL_COUNT    NUMBER(2)           DEFAULT 0        NOT NULL,
    LOGIN_LOCKED_AT     TIMESTAMP,
    HIRED_AT            DATE                NOT NULL,
    RETIRED_AT          DATE,
    CREATED_AT          TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UK_EMPLOYEE_NO UNIQUE (EMPLOYEE_NO),
    CONSTRAINT UK_EMPLOYEE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_EMPLOYEE_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID),
    CONSTRAINT CK_EMPLOYEE_ROLE CHECK (ROLE IN ('STAFF', 'MANAGER', 'SYSTEM_ADMIN')),
    CONSTRAINT CK_EMPLOYEE_STATUS CHECK (STATUS IN ('ACTIVE', 'ON_LEAVE', 'RETIRED')),
    CONSTRAINT CK_EMPLOYEE_TEMP_PW CHECK (TEMP_PW_YN IN ('Y', 'N')),
    -- 퇴사 상태와 퇴사일은 함께 존재
    CONSTRAINT CK_EMPLOYEE_RETIRED CHECK (
        (STATUS = 'RETIRED' AND RETIRED_AT IS NOT NULL) OR (STATUS <> 'RETIRED' AND RETIRED_AT IS NULL)
    )
);

CREATE INDEX IX_EMPLOYEE_BRANCH ON EMPLOYEE (BRANCH_ID);

COMMENT ON TABLE  EMPLOYEE IS '은행 직원 (고객 MEMBER와 분리)';
COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_NO IS '사번 - 직원 로그인 아이디';
COMMENT ON COLUMN EMPLOYEE.BRANCH_ID IS '소속 지점 (BRANCH_TYPE = BRANCH 인 행만, 본점 포함)';
COMMENT ON COLUMN EMPLOYEE.POSITION IS '직급 (사원/대리/과장/차장/부장/지점장 등) - 표시용, 권한과 무관';
COMMENT ON COLUMN EMPLOYEE.ROLE IS '권한: STAFF 일반 직원 / MANAGER 책임자 / SYSTEM_ADMIN 시스템 관리자';
COMMENT ON COLUMN EMPLOYEE.TEMP_PW_YN IS '임시 비밀번호 여부 - Y면 첫 로그인 시 비밀번호 변경 강제';


-- ---------------------------------------------------------------------
-- 4. IDENTITY_VERIFICATION : 본인확인(비대면 실명확인 mock) 심사 이력
--    반려 후 재신청 시 새 행을 추가한다 (기존 행 수정 X)
--    심사 권한: STAFF 이상
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_IDENTITY_VERIFICATION START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE IDENTITY_VERIFICATION (
    VERIFICATION_ID      NUMBER(19)          NOT NULL,
    MEMBER_ID            NUMBER(19)          NOT NULL,
    ID_CARD_TYPE         VARCHAR2(20)        NOT NULL,
    ID_ISSUE_DATE        DATE                NOT NULL,
    AUTH_BANK_NAME       VARCHAR2(30 CHAR)   NOT NULL,
    AUTH_ACCOUNT_MASKED  VARCHAR2(30)        NOT NULL,
    STATUS               VARCHAR2(20)        DEFAULT 'PENDING' NOT NULL,
    REJECT_REASON        VARCHAR2(500 CHAR),
    REQUESTED_AT         TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    REVIEWED_EMPLOYEE_ID NUMBER(19),
    REVIEWED_AT          TIMESTAMP,
    CONSTRAINT PK_IDENTITY_VERIFICATION PRIMARY KEY (VERIFICATION_ID),
    CONSTRAINT FK_IV_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_IV_EMPLOYEE FOREIGN KEY (REVIEWED_EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
    CONSTRAINT CK_IV_ID_CARD_TYPE CHECK (ID_CARD_TYPE IN ('RESIDENT_CARD', 'DRIVER_LICENSE')),
    CONSTRAINT CK_IV_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
    -- 반려 시 사유 필수
    CONSTRAINT CK_IV_REJECT_REASON CHECK (STATUS <> 'REJECTED' OR REJECT_REASON IS NOT NULL),
    -- 심사 완료 건은 심사 직원/일시 필수
    CONSTRAINT CK_IV_REVIEWED CHECK (STATUS = 'PENDING' OR (REVIEWED_EMPLOYEE_ID IS NOT NULL AND REVIEWED_AT IS NOT NULL))
);

-- 회원당 심사 대기(PENDING)는 1건만 허용 (Oracle은 NULL을 유니크 인덱스에서 제외)
CREATE UNIQUE INDEX UX_IV_ONE_PENDING
    ON IDENTITY_VERIFICATION (CASE WHEN STATUS = 'PENDING' THEN MEMBER_ID END);

CREATE INDEX IX_IV_MEMBER ON IDENTITY_VERIFICATION (MEMBER_ID, REQUESTED_AT);
CREATE INDEX IX_IV_STATUS ON IDENTITY_VERIFICATION (STATUS, REQUESTED_AT);

COMMENT ON TABLE  IDENTITY_VERIFICATION IS '본인확인 심사 이력 - 첫 입출금 계좌 개설 시 생성';
COMMENT ON COLUMN IDENTITY_VERIFICATION.AUTH_ACCOUNT_MASKED IS '1원 인증 타행 계좌번호 (마스킹 값만 저장)';


-- ---------------------------------------------------------------------
-- 5. LOGIN_LOG : 고객 로그인 이력 (추가만 하고 수정/삭제하지 않음)
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_LOGIN_LOG START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE LOGIN_LOG (
    LOGIN_LOG_ID        NUMBER(19)          NOT NULL,
    MEMBER_ID           NUMBER(19),
    LOGIN_ID_INPUT      VARCHAR2(30 CHAR)   NOT NULL,
    SUCCESS_YN          CHAR(1)             NOT NULL,
    FAIL_REASON         VARCHAR2(30),
    IP_ADDRESS          VARCHAR2(45)        NOT NULL,
    USER_AGENT          VARCHAR2(500),
    LOGIN_AT            TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_LOGIN_LOG PRIMARY KEY (LOGIN_LOG_ID),
    CONSTRAINT FK_LOGIN_LOG_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_LOGIN_LOG_SUCCESS CHECK (SUCCESS_YN IN ('Y', 'N')),
    CONSTRAINT CK_LOGIN_LOG_FAIL_REASON CHECK (
        FAIL_REASON IS NULL OR FAIL_REASON IN ('BAD_CREDENTIALS', 'LOGIN_LOCKED', 'SUSPENDED', 'WITHDRAWN', 'UNKNOWN_ID')
    ),
    CONSTRAINT CK_LOGIN_LOG_REASON_MATCH CHECK (
        (SUCCESS_YN = 'Y' AND FAIL_REASON IS NULL) OR (SUCCESS_YN = 'N' AND FAIL_REASON IS NOT NULL)
    )
);

CREATE INDEX IX_LOGIN_LOG_MEMBER ON LOGIN_LOG (MEMBER_ID, LOGIN_AT DESC);

COMMENT ON TABLE  LOGIN_LOG IS '고객 로그인 이력';
COMMENT ON COLUMN LOGIN_LOG.MEMBER_ID IS '존재하지 않는 아이디로 시도한 경우 NULL';


-- ---------------------------------------------------------------------
-- 6. EMPLOYEE_LOGIN_LOG : 직원 로그인 이력 (추가만 하고 수정/삭제하지 않음)
--    SYSTEM_ADMIN 이 관리자 활동 로그 화면에서 조회
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_EMPLOYEE_LOGIN_LOG START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE EMPLOYEE_LOGIN_LOG (
    LOGIN_LOG_ID        NUMBER(19)          NOT NULL,
    EMPLOYEE_ID         NUMBER(19),
    EMPLOYEE_NO_INPUT   VARCHAR2(30)        NOT NULL,
    SUCCESS_YN          CHAR(1)             NOT NULL,
    FAIL_REASON         VARCHAR2(30),
    IP_ADDRESS          VARCHAR2(45)        NOT NULL,
    USER_AGENT          VARCHAR2(500),
    LOGIN_AT            TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EMPLOYEE_LOGIN_LOG PRIMARY KEY (LOGIN_LOG_ID),
    CONSTRAINT FK_ELL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
    CONSTRAINT CK_ELL_SUCCESS CHECK (SUCCESS_YN IN ('Y', 'N')),
    CONSTRAINT CK_ELL_FAIL_REASON CHECK (
        FAIL_REASON IS NULL OR FAIL_REASON IN ('BAD_CREDENTIALS', 'LOGIN_LOCKED', 'ON_LEAVE', 'RETIRED', 'UNKNOWN_ID')
    ),
    CONSTRAINT CK_ELL_REASON_MATCH CHECK (
        (SUCCESS_YN = 'Y' AND FAIL_REASON IS NULL) OR (SUCCESS_YN = 'N' AND FAIL_REASON IS NOT NULL)
    )
);

CREATE INDEX IX_ELL_EMPLOYEE ON EMPLOYEE_LOGIN_LOG (EMPLOYEE_ID, LOGIN_AT DESC);
CREATE INDEX IX_ELL_LOGIN_AT ON EMPLOYEE_LOGIN_LOG (LOGIN_AT DESC);

COMMENT ON TABLE  EMPLOYEE_LOGIN_LOG IS '직원 로그인 이력';
COMMENT ON COLUMN EMPLOYEE_LOGIN_LOG.EMPLOYEE_ID IS '존재하지 않는 사번으로 시도한 경우 NULL';


-- ---------------------------------------------------------------------
-- 7. TRANSFER_LIMIT_REQUEST : 이체한도 변경 신청 (마이페이지 보안설정 13.5)
--    신청: 팀원1 / 승인 화면: 팀원4 / 실제 한도 반영: 팀원2(ACCOUNT)
--    감액(희망 < 현재): 신청 즉시 APPROVED, 심사 직원 없음 (한도를 내리면 더 안전하므로)
--    증액(희망 > 현재): PENDING → MANAGER 심사
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_TRANSFER_LIMIT_REQUEST START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE TRANSFER_LIMIT_REQUEST (
    REQUEST_ID           NUMBER(19)          NOT NULL,
    MEMBER_ID            NUMBER(19)          NOT NULL,
    ACCOUNT_ID           NUMBER(19)          NOT NULL,
    CURRENT_LIMIT        NUMBER(15)          NOT NULL,
    REQUESTED_LIMIT      NUMBER(15)          NOT NULL,
    REASON               VARCHAR2(300 CHAR)  NOT NULL,
    STATUS               VARCHAR2(20)        DEFAULT 'PENDING' NOT NULL,
    REJECT_REASON        VARCHAR2(500 CHAR),
    REVIEWED_EMPLOYEE_ID NUMBER(19),
    REVIEWED_AT          TIMESTAMP,
    CREATED_AT           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    CONSTRAINT PK_TRANSFER_LIMIT_REQUEST PRIMARY KEY (REQUEST_ID),
    CONSTRAINT FK_TLR_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_TLR_EMPLOYEE FOREIGN KEY (REVIEWED_EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
    CONSTRAINT CK_TLR_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT CK_TLR_LIMIT CHECK (CURRENT_LIMIT >= 0 AND REQUESTED_LIMIT > 0 AND REQUESTED_LIMIT <> CURRENT_LIMIT),
    CONSTRAINT CK_TLR_REJECT_REASON CHECK (STATUS <> 'REJECTED' OR REJECT_REASON IS NOT NULL),
    -- 감액은 항상 즉시 승인(APPROVED)이며 심사 직원·심사일시가 없다
    CONSTRAINT CK_TLR_DECREASE_AUTO CHECK (
        REQUESTED_LIMIT > CURRENT_LIMIT
        OR (STATUS = 'APPROVED' AND REVIEWED_EMPLOYEE_ID IS NULL AND REVIEWED_AT IS NULL)
    ),
    -- 심사가 끝난 증액 건은 심사 직원·심사일시 필수
    CONSTRAINT CK_TLR_REVIEWED CHECK (
        STATUS = 'PENDING' OR REQUESTED_LIMIT < CURRENT_LIMIT
        OR (REVIEWED_EMPLOYEE_ID IS NOT NULL AND REVIEWED_AT IS NOT NULL)
    )
);

-- 계좌당 심사 대기 신청은 1건만 (PENDING은 증액 신청만 존재)
CREATE UNIQUE INDEX UX_TLR_ONE_PENDING
    ON TRANSFER_LIMIT_REQUEST (CASE WHEN STATUS = 'PENDING' THEN ACCOUNT_ID END);

CREATE INDEX IX_TLR_STATUS ON TRANSFER_LIMIT_REQUEST (STATUS, CREATED_AT);
CREATE INDEX IX_TLR_MEMBER ON TRANSFER_LIMIT_REQUEST (MEMBER_ID, CREATED_AT);

COMMENT ON TABLE  TRANSFER_LIMIT_REQUEST IS '이체한도 변경 신청';
COMMENT ON COLUMN TRANSFER_LIMIT_REQUEST.CURRENT_LIMIT IS '신청 시점의 1일 이체한도 (원)';


-- =====================================================================
-- ACCOUNT 테이블(팀원2) 생성 후 실행
-- =====================================================================
-- ALTER TABLE TRANSFER_LIMIT_REQUEST
--     ADD CONSTRAINT FK_TLR_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID);
